### ISSUE TITLE
accepting more than one operator at a time

### ISSUE THREAD

**Issue by emht** [MohitChattlani/Simple-Calculator#1]
![capture](https://cloud.githubusercontent.com/assets/21521341/20465008/b3f2da04-af79-11e6-96b0-4bef77463d36.PNG)

as a input more than one operators are being accepted.
Once a calculation is made, next input continues with previous ones without clearing the input.

**Comment by MohitChattlani** [comment]
I have fixed the following issues in my recent commits . Now you can give it a go ! Thanks for the issue though.
