### ISSUE TITLE
Make the calculator display more mobile friendly by changing its CSS. Currently it looks awkward on mobiles. 

### ISSUE THREAD

**Issue by MohitChattlani** [MohitChattlani/Simple-Calculator#12]

**Comment by reece-bennett** [comment]
I'll have a go at this :)

**Comment by DulanDev** [comment]
I think it still needs to be more responsive. I'll add some media queries to make it look good on mobile.

**Comment by MohitChattlani** [comment]
let me review your code @PhyscoKillerMonkey @Dulan666 .
