### ISSUE TITLE
Improve aesthetics of calculator

### ISSUE THREAD

**Issue by reece-bennett** [MohitChattlani/Simple-Calculator#16]
I've been playing around with the style of the calculator a little bit, here is what I'e come up with:

Before | After
------- | -----
![image](https://user-images.githubusercontent.com/6674785/31547748-61734cd4-b020-11e7-97e2-3d4f5b621bc0.png) | ![image](https://user-images.githubusercontent.com/6674785/31547760-6b39d03a-b020-11e7-9d80-97de8dccd183.png)

It uses a table rather than the original list of buttons and break-lines. Obviously buttons could be changed around, I wasn't sure how to fill the top two left buttons hence the brackets.

@MohitChattlani would you be interested with a PR for this?

**Comment by MohitChattlani** [comment]
let me have a look at this @PhyscoKillerMonkey

**Comment by MohitChattlani** [comment]
yes make a pr.

**Comment by MohitChattlani** [comment]
the pr has been merged @PhyscoKillerMonkey. Thanks.
