### ISSUE TITLE
The Calculator is accepting alphanumeric keys(A-Z) along with numeric input. To disable alphanumeric key inputs.

### ISSUE THREAD

**Issue by MohitChattlani** [MohitChattlani/Simple-Calculator#6]

**Comment by chanunegi** [comment]
ok i will

**Comment by ivanelianto** [comment]
I remove the logic expression that check the user input and it's work. Because, the ASCII code for the number is only in the first logic expression. I think the second expression (after or) is unnecessary.

**Comment by MohitChattlani** [comment]
Let me check your work @chanunegi @purenaturalism

**Comment by bhatiatanish** [comment]
Is the issue still open or fixed? @MohitChattlani

**Comment by reece-bennett** [comment]
I was looking to start work on this issue but I notice PR #9 claims to have fixed it. Is that the case and if so should it be merged? @MohitChattlani

**Comment by MohitChattlani** [comment]
it has been fixed @bhatiatanish @PhyscoKillerMonkey
